### ISSUE TITLE
'screen' utiltity: permissions issues

### ISSUE THREAD

**Issue by grufwub** [WhitewaterFoundry/WLE#11]
I did find an issue with the 'screen' the utility that I'm pretty sure happens across all WSL distros, as it's down to a socket-cleaning service that normally runs on shutdown needing to be manually run. Closing the console window each time doesn't seem to count as a shutdown? But based on the nature of the issue, I wouldn't be surprised if it's something we might run into with other programs and something we could look into workarounds for in our distribution.

But, I don't run into it on WLE... Instead, the first run of screen upon every open of a console window gives a "Cannot make directory '/run/var/screen': Permission denied". However after running screen once with admin permissions, this issue is resolved until next open of a console window.

This different issue on WLE might be down to a permissions based issue similar to #8, or it may be another issue with screen itself, but thought it better to mention than not. If it is a permissions issue, clearing it up may then reveal the original issue noted.

**Comment by sirredbeard** [comment]
I will generate new rootfs to work with.

I wonder if we need to look at permissions set on .tar.gz.

**Comment by grufwub** [comment]
Ah yeah that would make sense for our CentOS build. The issue on the more debian based distros was that .screen wasn't being emptied on console window close

**Comment by sirredbeard** [comment]
We should definitely patch that if it is an issue on WLinux.
