### ISSUE TITLE
[Feature] Post-install script (à la WLinux)

### ISSUE THREAD

**Issue by nunix** [WhitewaterFoundry/WLE#19]
I just created a first `install.tar.gz` with the script `create-targz.sh` and I noticed that `sudo` (for example) was not installed.

As the script is "consumed" as is from CentOS, I think that a sort of post-install script (such as the one from WLinux) could be a very good added value.

**Comment by sirredbeard** [comment]
WLinux will remain the primary consumer-facing product of WF in the Microsoft Store with all the features of wlinux-setup and extensive customizations.

WLE is a template for custom enterprise deployments which can be further customized via Kickstart file where sysadmins need control over specific packages for compliance and auditing purposes.

Two very different markets and solutions.

WLE was developed for a specific new enterprise partnership WF is developing.

There are no current plans to bring wlinux-setup to WLE or WLE to the Microsoft Store except for demos at this time.

**Comment by nunix** [comment]
hmm ok, makes sense 😁
Then just let me know “how” you forsee the publicity part. Should we start showing it off?

Also, I will try to build the `install.tar.gz` from wle (creation inception 😁)

if it works, then the current `install.tar.gz` can be considered as a builder version, should I upload it for us to use? or do you want to keep only the script available?

great work team 🙌

**Comment by sirredbeard** [comment]
It is a slow rollout for now. You can post about it any time on Twitter. It is here and public.

You can distribute any install.tar.gz you made but WF will not.

For now it is just the script and template. It is not it's own distribution for widespread use, it is a custom solution for enterprise.

Average users who want to try WSL still get the best experience from WLinux.

If someone were to fork WLE for their own "compatible" distro on the Store I would not be upset.

**Comment by nunix** [comment]
thanks a lot for the answer and personally I won’t publish anything (other else I would have done it long time ago with the Corsair distro 🤣)

My point is more: in case someone asks to where to get WLE, then I will redirect them to this GH repo.
As for the install file, it was more for “us” now rather than adding it publicly.

Anyway thanks again and I simply want to ensure I do not cause any trouble while sharing the word about this distro 😅

**Comment by sirredbeard** [comment]
Maybe we can make something work on the Store.

**Comment by sirredbeard** [comment]
Stay tuned.
