### ISSUE TITLE
/etc/shadow is world readable

### ISSUE THREAD

**Issue by imgrant** [WhitewaterFoundry/WLE#67]
**Describe the bug**
`/etc/shadow` is world-readable

**To Reproduce**
1. Install Pengwin Enterprise 8 (e.g. from Microsoft Store, as I did)
2. Start Penwing Enterprise, and follow the create a new user process that is kickstarted
3. This involves setting a root password, a new username, and a password for the user
4. Check the permissions on `/etc/shadow` (`ls -lh /etc/shadow`)
5. Observe it is world readable:

```bash
[ian@pengwin8 ~]$ ls -lh /etc/shadow*
-rw-r--r-- 1 root root 706 Oct 19 11:24 /etc/shadow
-rw-r--r-- 1 root root 576 Oct 19 11:24 /etc/shadow-
```

**Expected behavior**
`/etc/shadow` should probably have tighter restrictions, no? It does usually in most (all?) Linux installations.

**Additional context**
Clearly the security implications are probably less severe in the WSL context, but best practice should still be adhered to.

Insert here:

**~WLinux~ Pengwin Enterprise 8 Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: **8.4.9.0**

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

OS Name:                   **Microsoft Windows 11 Pro**
OS Version:                **10.0.22000 N/A Build 22000**
OS Manufacturer:           **Microsoft Corporation**
OS Configuration:          **Standalone Workstation**
OS Build Type:             **Multiprocessor Free**
BIOS Version:              **Dell Inc. 1.16.0, 09/07/2021**

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. We will check, probably the permissions were changed during the image creation.

Regards,
Carlos
